config/routes.rb
Rails.application.routes.draw do
  resources :products

end

app/models/product.rb
class MySpecialError < StandardError
  def messsge
    "bbobobobo"
  end
end
class Product < ActiveRecord::Base

  attr_accessor :select_box

# validates

  # validates :title, presence: true, on: [:create]
  # validates :title, uniqueness: true, unless: Proc.new { |a| title == "hi there" }
  # validates :title, presence: true, unless: Proc.new { title.blank? }
  # validates :title, confirmation: true, if: Proc.new { title.blank? }
  # validates :title, presence: true, allow_blank: true
  # validates :title, presence: true, allow_nil: true
  # validates :title, presence: true, strict: MySpecialError

# => 1. validates_absence_of

  # validates :enabled, absence: { message: "you should not enter blank value of %{attribute}" }
  # validates :select_box, absence: true
  # validates_absence_of :title, message: "must be boobobo"


# => 2. validates_acceptance_of

  #default datatype of accept option is string any other option will not work in anyway
  #acceptance has a problem working with nil
  #if you give nil as value of attributes it is accepted for every condition

  # validates_acceptance_of :title, accept: "hi there", message: "must be 'hi there'"
  # validates :title, acceptance: true, allow_nil: false
  # validates :title, acceptance: { accept: "hi there", message: "must be 'hi there'" }
  # validates :enabled, acceptance: true      #it will not work
  # validates :enabled, acceptance: { accept: "0" }    #it will not work either
  # validates :enabled, acceptance: { accept: false }    #it will work only
  # validates :ena, acceptance: { accept: "yes" }

# => 3. validates_confirmation_of

  #It also doesnt work if title is nil or true but it certainly works if title is false!

  # validates_confirmation_of :title
  # validates :title, confirmation: { message: "gvjdndnkf" }

# => 4. validates_exclusion_of

  #in or within option is mandatory for validates_exclusion_of otherwise it shows error
  # validates_exclusion_of :title, within: ->(person){ print person }
  #the argument person passed in is the object itself its testcase is as follows
  # validates_exclusion_of :password, within: ->(person) { [person.username, paerson.first_name, person.phone_no] }

  # validates :title, exclusion: %w( mov avi )

  # validates :select_box, exclusion: { in: 0..2 }
  #exclusion will not care if the conditional attribute is not in the database
  #object is always created

  # validates :title, exclusion: { within: %w(hey ho), message: "ishgoifbyi" }
  # validates :title, exclusion: { within: nil, message: "ishgoifbyi" }
  #can not give nil it will throw an error

# => 5. validates_format_of

  # validates_format_of :description, with: /.[jpg|gif]/, without: /.gif/
  #both with or without can not be supplied but one is must

  # validates_format_of :description, with: /\.(jpg|gif)/
  # validates_format_of :description, without: /\.gif/

  # validates_format_of :description, with: /^(jpg)+$/
  # validates_format_of :description, with: /\A(jpg)+\z/
  # validates_format_of :description, with: /^(jpg)+$/, multiline: true
  #safely use \A \z option while using multiline options ^ $ multiline => true needs to be determined

  #if the value is nil regex works object is not saved unless allow_nil is mentioned explicitly

  # validates :image_url, format: { with: /\.(jpg|gif)/, message: "is not in correct format" }

# => 6. validates_inclusion_of

  # validates :select_box, inclusion: { in: ["0","1","2"] }
  #object is never created if the given attribute is not in database

  #Also inclusion works as same way as exclusion

# => 7. validates_length_of

  #if the value is nil then it is not considered for length 0 even, object is not saved
  # validates_length_of :title, in: 0..9, message: "dguk"
  # in and within must be a range
  #if you specify message it replaces all three default messages

  # validates_length_of :title, is: 2
  #nonNegative Integer Or Infinity

  # validates_length_of :title, minimum: 2, maximum: 5
  #you can provide range using in or within or by using minimum and maximum

  # validates_length_of :permalink, is: 3, tokenizer: ->(str) { str.split('-') }

  # validates :permalink, length: {
  #   in: 5..6,
  #   tokenizer: ->(str) { str.split('-') },
  #   message: "booboobo0"
  # }

  # validates :permalink, length: {
  #   in: 6..8,
  #   minimum: 4,
  #   maximum: 7,
  #   is: 6,
  #   within: 1..9
  # }
  #In this case priority is given to in or within over minimum and maximum
  #first of in or within is considered as range given
  #first range is checked then accurate value is checked

# => 8. validates_numericality_of

  # validates_numericality_of :permalink, only_integer: true
  # validates_numericality_of :permalink, greater_than: 30.23, only_integer: true
  #if specified only_integer it check if it is a integer or not and shows only that error
  #further validations are skipped if it gives error

  # validates_numericality_of :permalink, other_than: :boo
  # validates_numericality_of :permalink, other_than: 23
  #error thrown is just its not a number

  # validates_numericality_of :permalink, odd: true
  # validates_numericality_of :permalink, even: true
  # even in only integer: false this validation removes decimal points just checks before of it
  #for odd and even without any rounding off

  # validates :permalink, numericality: {
  #   only_integer: true,
  #   greater_than: 12,
  #   less_than: 56,       #sequence
  #   other_than: 23,
  #   message: "boo"
  # }
  #same as length option, the message option will replace every kind of message

# => 9. validates_presence_of

  # validates_presence_of :title, :enabled, presence: true
  # it calls the blank? method on attribute
  # here anabled is a checkbox if not checked value goes as "0" which is mapped to false but false.blank? = true
  # even whitespaces are also considered blank

  # validates_presence_of :title, message: "fhg"

# => 10. validates_size_of

  # Alias for validates_length_of

  # validates :permalink, size: {
  #   in: 5..6,
  #   tokenizer: ->(str) { str.split('-') },
  #   message: "yoohoo"
  # }
  #this type in validates does not work

  # validates_size_of :permalink, is: 3, tokenizer: ->(str) { str.split('-') }
  #while this type works fine

# => 11. validates_uniqueness_of

  # validates_uniqueness_of :title, scope: :category
  #even if the category is nil there can only be one value of title for null category

  # validates_uniqueness_of :title, case_sensitive: false
  #affect the query by including binary

  # validates_uniqueness_of :title, conditions: -> { where(description: "") }
  #it only works for db methods like where not general if else works inside the block
  #self is the ActiveRecord::Relation object of the newly current created object

  # validates :title, uniqueness: {
  #   scope: [:category, :permalink],
  #   case_sensitive: false,
  #   conditions: -> { where(description: "hey there") }
  # }

  # validates_uniqueness_of :title, conditions: lambda { |post, pos| where(description: "") }
  # validates_uniqueness_of :title, conditions: ->(post) { where(description: "") }
  #shows some error needs to discuss

  validates :title, presence: true

  private


    def boo
      [23,24,25]
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :price, :discount_price, :enabled, :image_url, :category, :images, :permalink, :description)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :discount_price %><br>
    <%= f.text_field :discount_price %>
  </div>
  <div class="field">
    <%= f.label :enabled %><br>
    <%= f.check_box :enabled %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :images %><br>
    <%= f.file_field :images %>
  </div>
  <div class="field">
    <%= f.label :permalink %><br>
    <%= f.text_field :permalink %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :select_box %>
    <%= f.select :select_box, [0,1,2,3,4,5], prompt: "Select One", include_blank: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Discount price</th>
      <th>Enabled</th>
      <th>Image url</th>
      <th>Category</th>
      <th>Images</th>
      <th>Permalink</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.price %></td>
        <td><%= product.discount_price %></td>
        <td><%= product.enabled %></td>
        <td><%= product.image_url %></td>
        <td><%= product.category %></td>
        <td><%= product.images %></td>
        <td><%= product.permalink %></td>
        <td><%= product.description %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Discount price:</strong>
  <%= @product.discount_price %>
</p>

<p>
  <strong>Enabled:</strong>
  <%= @product.enabled %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<p>
  <strong>Images:</strong>
  <%= @product.images %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @product.permalink %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>